### ISSUE TITLE
windows binary download fails: web page loop.

### ISSUE THREAD

**Issue by rcrath** [theriex/digger#17]
When I download through the diggerhub website, the file loops to a broken version of hte same page.  Clicking on download send it back to same broken page, but in downloads folder: 
reproduce: 
1. Click once on windows binary at diggerhub.com. Result, land on same page but broken with url `https://diggerhub.com/downloads/digger-win.exe`  
2. Click withing that page sends back to same broken bage again, : https://diggerhub.com/downloads/downloads/digger-win.exe
3. repeat and get https://diggerhub.com/downloads/downloads/downloads/digger-win.exe
4. etc.
Workaround (choose one): 
A: Download binary release from github.
D. Try Node.Js method
B. use a free OS
c: buy a mac
:)

**Comment by theriex** [comment]
It would appear many browsers feel that downloading windows exe files directly is a bad thing.  They are probably right.  Packaging it into a zip seems to enable downloading, and hopefully it should work after unzip.  That's probably the most straightforward approach for now unless node pkg gains a capability of creating something downloadable.

Site updated.  Thanks for pointing that out.
